# Generated by Django 4.1.7 on 2023-03-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_protocolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='categoria_manuntecao',
            new_name='categoria_manuntencao',
        ),
    ]
