# Generated by Django 4.1.7 on 2023-03-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_rename_categoria_manuntecao_servico_categoria_manuntencao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='categoria_manuntencao',
            new_name='categoria_manutencao',
        ),
    ]
