# Generated by Django 4.1.7 on 2023-03-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_rename_categoria_manuntencao_servico_categoria_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
